name: Android CI

on:
  workflow_dispatch:

jobs:
  buildArm:
    name: Build Arm Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up KeyStore Password
        shell: bash 
        if: ${{ env.KEYSTOREPASSWORD != '' }}
        env:
          KEYSTOREPASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
        run: |
          printf 'KEYSTOREPASSWORD<<EOF\n%s\nEOF\n' "$KEYSTOREPASSWORD" >> $GITHUB_ENV
        
      - name: Set up Firebase
        shell: bash 
        if: ${{ env.Firebase != '' }}
        env:
          Firebase: ${{ secrets.Firebase }}
        run: |
          printf 'Firebase<<EOF\n%s\nEOF\n' "$Firebase" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleArmDebug
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: android-appstudio-armeabi-v7a
          path: app/build/outputs/apk/arm/debug/app-arm-debug.apk

      - name: Upload output metadata APK
        uses: actions/upload-artifact@v3
        with:
          name: output-metadata-armeabi-v7a
          path: app/build/outputs/apk/arm/debug/output-metadata.json

  buildAarch64:
    name: Build Aarch64 Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up KeyStore Password
        shell: bash 
        if: ${{ env.KEYSTOREPASSWORD != '' }}
        env:
          KEYSTOREPASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
        run: |
          printf 'KEYSTOREPASSWORD<<EOF\n%s\nEOF\n' "$KEYSTOREPASSWORD" >> $GITHUB_ENV
        
      - name: Set up Firebase
        shell: bash 
        if: ${{ env.Firebase != '' }}
        env:
          Firebase: ${{ secrets.Firebase }}
        run: |
          printf 'Firebase<<EOF\n%s\nEOF\n' "$Firebase" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleAarch64Debug
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: android-appstudio-armeabi-v8a
          path: app/build/outputs/apk/aarch64/debug/app-aarch64-debug.apk

      - name: Upload output metadata APK
        uses: actions/upload-artifact@v3
        with:
          name: output-metadata-armeabi-v8a
          path: app/build/outputs/apk/aarch64/debug/output-metadata.json
