name: LogicEditor Test

on:
  workflow_dispatch:
  push:
    paths:
      - test/logiceditor
      - beans
      - logiceditor

jobs:
  build:
    name: Build LogicEditor Test Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew :test:logiceditor:assembleDebug
          
      - name: Upload LogicEditor Test debug APK
        uses: actions/upload-artifact@v4
        with:
          name: logiceditor-test
          path: test/logiceditor/build/outputs/apk/debug/logiceditor-debug.apk

      - name: Upload build output metadata
        uses: actions/upload-artifact@v4
        with:
          name: output-metadata-logiceditor-test
          path: test/logiceditor/build/outputs/apk/debug/output-metadata.json
